open-dynaMIX/simple-mpv-webui

webui-page/index.html, webui.lua
Additionally to seeking and skipping files, seeking chapters is useful
too. Users might want to quickly navigate to where they left off in a
full-length movie, or skip repeating intro/outro sections of TV series.
=> Add chapter seeking buttons

README.md, webui-page/index.html, webui-page/webui.css, webui-page/webui.js, webui.lua
Thsi commit adds the following features:
- add `chapter` and `chapters` to the status response
- if chapters are available, diplay info in top table
- if no chapters are available, disable chapter seeking buttons
=> feat(chapters): display chapter info and handle missing chapters

.gitignore, helpers/generate_changelog.sh, webui.lua
`webui.lua` now contains a `VERSION` variable and global variables are
now upper case.
For generating the changelog, we use `python-semantic-release`. This
commit also adds a small helper script with the commands used for this.
=> chore(release): add version variable and changelog tooling

webui.lua
The startup notification was displayed right on startup. That meant,
that when loading file that takes some time (a stream for example), the
message was barely or not visible at all.
This commit implements using the `file-loaded` event for displaying the
notification. That way we can be sure, the window is properly loaded.
Additionally the version is now also displayed in the notification.
=> fix: use events for sending startup notification

webui-page/index.html, webui.lua
This commit refactors the way the status response json is built. It now
uses `mp.utils.format_json()`.
Additionally, the preparation of the data is made more readable and the
rounding of certain values has been removed.
=> feat(status): do not round time and volume values

README.md, webui.lua
This commit adds a new key "audio-support" to the status response json.
It is `false` if the only audio device found by mpv is `auto`. As this
can be subject to change, it gets reevaluated on every `/status`
request.
Related to #27
=> feat(audio): add "audio-support" to status response

tests/tests.py
This commit makes sure that in the playlist tests, we're not removing
the currently playing track. If doing so, mpv will quit.
=> chore(tests): fix flaky playlist test

webui.lua
The selection of available audio-devices can change during runtime. This
commit makes sure they are not only checked at startup, but for every
request, that depends on them.
=> fix: rebuild audio-devices during runtime

tests/conftest.py, tests/tests.py, webui.lua
This commit implements a new option `htpasswd_path`. This allows for
setting a custom path to the `.htpasswd` file.
BREAKING CHANGE: .htpasswd file is not auto-detected anymore. This
change is needed, because there are users that have the webui installed
through a package manager. This makes adding the file to the directory
where `webui.lua` cumbersome.
=> feat(auth): make htpasswd path configurable

tests/tests.py
Using `None` with `HTTPBasicAuth` is deprecated. This commit replaces
`None` with an empty string.
=> chore: do not use None in HTTPBasicAuth

README.md, webui.lua
Showing the raw string ".htpasswd" makes it seem like that's the file
that was searched.  Use the option name instead and include the user
setting directly to make it clear.
=> docs: improve htpasswd error message & documentation

webui-page/webui.js
Refreshing every second is a bit wasteful when the page is in the
background.  Use the new Page Lifecycle API to detect when it is
active and flip between refresh rates accordingly.
=> feat: lower refresh rate when page is not active

webui-page/webui.js
The current 1sec delay can make the UI feel a bit laggy, so kick off
an refresh sooner whenever we react to user input.
=> feat: refresh UI quicker when user is interacting

webui-page/webui.js
These were never populated so clients had to assume details leading
to weird behavior: Chrome would just default to a length of 5sec and
then keep looping that range over & over.
=> feat: update mediaSession playback state & position info

webui-page/index.html, webui-page/webui.js
This allows the user to see what they'll set the slider to before
they actually click.
=> feat: set tooltip text on sliders dynamically

webui-page/webui.js
On some browsers (e.g. qutebrowser), `navigator.mediaSession.setPositionState`
throws an `is not a function` error. This commit implements a check for
the availability of the function, before calling it.
It also moves the calling of `setPositionState()` into `setupNotification()`.
=> fix(js): only use setPositionState if available

webui-page/webui.js
This commit removes the blocking of the sliders after firing a request.
Never really worked.
=> chore(js): remove block{Pos,Vol}Slider

webui-page/webui.js
This commit makes sure that media metadata is sanitized before usage in
HTML. This prevents a theoretical XSS. An attacker would need to be able
to modify the media file played by MPV.
Thanks to @marben-olvbar for pointing this out.
=> fix(js): sanitize metadata in order to prevent unlikely XSS

tests/snapshots/snap_tests.py, tests/tests.py, webui.lua
This commit refactores the handling of requests in the API. All
endpoints are added as functions to a table. A new `response` table is
introduced. Every endpoint function returns such response.
This allows for more generic request handling, while offering even more
customizability per request. As a side effect, the `Allow:` header now
contains the correct methods instead of hardcoded `GET,POST`.
=> fix(api): refactor request handling; fix `Allow` header

README.md, main.lua, tests/snapshots/snap_tests.py, webui-page/index.html, webui-page/webui.js
=> feat: make new properties "start" and "end" available
